apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-skynet
spec:
  selector:
    matchLabels:
      app: deno-skynet
  replicas: 3
  template:
    metadata:
      labels:
        app: deno-skynet
    spec:
      containers:
        - name: deno-skynet
          image: quay.io/alecmerdler/deno-skynet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
